language: ruby
rvm:
- 2.0.0
before_script:
- "npm install bower"
- "bower install"
script: "bundle exec middleman build"
before_deploy: "cd build"
deploy:
  provider: s3
  bucket: closure.jp
  skip_cleanup: true
  secret_access_key:
    secure: BD/BS6ksBUaZll2/ELUALftJ2R2cfI/BltmWvZAeI9M3F5zmMTycoczn+aM7J9CT66oKCttH/ieNOo2hNFJC4xlkYnT0E5IasJCy+KJ08dZy1mflnvdHR3R1UudFTq957LsswnFRj/Ro2IGyWitmSctCjpEmrED6bf7RzLGLYFE=
  access_key_id:
    secure: eH84ovlzDFhlk2euM4xapNakIiaXtBSL9DHoUCPPWJMfBPHQOFm0ut0237Z5zNKu5vk3Hn/jcPkFnIVkLT4z7IKBzKd3/3t3TKUCUEbdLwHWqNwYKonCpnRt6AtBBvSNjZY+mkfMLyXkUv3iL8gRoWH0Rm0ayxBHFAWbNIjRG+E=
